version: "3.9"
networks:
  go-logger:
    name: go-logger
services:
  go-service-app:
    build: .
    image: sing3demons/gin-backend-api:0.1
    container_name: go-backend
    networks:
      - go-logger
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: sing3demons/gin-backend-api:0.1
    # volumes:
    #   - ./logs:/logs
    # prometheus:
    #   image: prom/prometheus:latest
    #   volumes:
    #     - ./prometheus:/etc/prometheus/
    #   command:
    #     - '--config.file=/etc/prometheus/prometheus.yml'
    #     - '--storage.tsdb.path=/prometheus'
    #   ports:
    #     - "9090:9090"
    #   depends_on:
    #     - go-service-app
    # grafana:
    #   image: grafana/grafana:latest
    #   #    volumes: 
    #   #      - grafana_data:/var/lib/grafana
    #   environment:
    #     - GF_SECURITY_ADMIN_PASSWORD=admin
    #   depends_on:
    #     - prometheus
    #   ports:
    #     - "3000:3000"
    # fluentd:
    #   image: fluent/fluentd:latest
    #   ports:
    #     - "24224:24224"
    #   volumes:
    #     - ./docker.conf:/fluentd/etc/docker.conf
    #   environment:
    #     - FLUENTD_CONF=docker.conf
